### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ethsmith** [N1T3SLAY3R/Empirecraft#2]
I got an idea of the first few things I want to do to continue the plugin but before I can work on them I need your help one time xD I sent you a pm on bukkit dev with a few requests/questions so that I can start working on the code for the continuation. Could you please check your Bukkit Dev PM, Thanks in advance!

**Comment by sgdc3** [comment]
@TekkitCommando so? Any good news? ;)

**Comment by ethsmith** [comment]
@sgdc3 I am now the official maintainer of Empirecraft :D and the first thing I am doing is working on the building creation code.

**Comment by sgdc3** [comment]
Nice ;)

**Comment by ethsmith** [comment]
Yep!
